### ISSUE TITLE
76561199334006667

### ISSUE THREAD

**Issue by kartoplyan** [BalconyStudios/sandbox-server#1]
короче адмін я випадково заспавнив якусь фігню з дублікацій,вона навіть великою не була я дійсно випадково це зробив.якщо потрібно я можу особисто вам розповісти в діскорді як це було.Дуже подобається цей сервер і бути на ньому у бані ще 2 неділі буде дуже сумно(

**Comment by kartoplyan** [comment]
мій діскорд-Гриша Семечкин#6077

**Comment by UAVXP** [comment]
Добре, розбанив. Наступного разу, будь-ласка, обережніше
